### ISSUE TITLE
Bower Design System - Bootstrap 3.3.5 Issues

### ISSUE THREAD

**Issue by ldaug** [PBGUX/bower-designsystem#1]
Changed my projects to use bower to install DS 2.2.1. This requires Bootstrap 3.3.5, which I also updated. But 3.3.5 apparently has changes to it that prevent bower from injecting the bootstrap css into  the projects index.html. To get this to work I changed my bower to reference 3.3.4 (something I also notice in the ds bower.json file).

**Comment by danielcollettepb** [comment]
Took me a bit to understand, but I think I follow you now...

The DS bower.json has a dependency of Bootstrap 3.3.4 which we think is installed by another package  OR left over from a previous version (need to investigate this a bit). We currently use the CDN of 3.3.5 in the index.html for the CSS.... but you found a bug since we reference the 3.3.4 JS in the bower_component. Adding this as a task to fix (Thanks!)

The bower-designsystem is correct by referencing Bootstrap 3.3.5

Are you using a grunt/gulp task to inject the files into the index.html? Bower would not do this automatically.

**Comment by ldaug** [comment]
It's in grunt:

    'bower-install': {
      app: {
        html: '<%= datahub.src %>/index.html',
        ignorePath: '<%= datahub.src %>/'
      }
    },

And then the Index.html:

    
    
    <link rel="stylesheet" href="vendor/bower_components/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="vendor/bower_components/bower-designsystem/dist/css/design_system.css" />
    
    

I googled this issue, and found many posts from upset users about the change in 3.3.5. I tried the overrides suggested here and didn't get it to work.

https://github.com/twbs/bootstrap/issues/16663

**Comment by nickroberts** [comment]
You can override the `main` property in the `bower.json` to only include what you need, if this is what you're talking about. We are doing this in the shipping app with several different bower packages.

**Comment by lombardi-gux** [comment]
FWIW We don't try to insert Bootstrap into the wiredep section on the DS2 web site.  We have bootstrap served from a CDN.

From: ldaug
Reply-To: PBGUX/bower-designsystem
Date: Wednesday, October 14, 2015 at 1:38 PM
To: PBGUX/bower-designsystem
Subject: Re: [bower-designsystem] Bower Design System - Bootstrap 3.3.5 Issues (#1)


It's in grunt:

'bower-install': {
  app: {
    html: '<%= datahub.src %>/index.html',
    ignorePath: '<%= datahub.src %>/'
  }
},


And then the Index.html:



<link rel="stylesheet" href="vendor/bower_components/bootstrap/dist/css/bootstrap.css" />
<link rel="stylesheet" href="vendor/bower_components/bower-designsystem/dist/css/design_system.css" />




I googled this issue, and found many posts from upset users about the change in 3.3.5. I tried the overrides suggested here and didn't get it to work.

twbs/bootstrap#16663<https://github.com/twbs/bootstrap/issues/16663>

—
Reply to this email directly or view it on GitHub<https://github.com/PBGUX/bower-designsystem/issues/1#issuecomment-148129355>.

________________________________

**Comment by ldaug** [comment]
For some reason the overrides doesn't work for me. I'll keep looking into it on my end, but want to point this out in case others are doing what I am.

**Comment by danielcollettepb** [comment]
closing as this is related to Grunt. Thanks for submitting the issue for others.

**Comment by danielcollettepb** [comment]
really closing now... also check [#2](https://github.com/PBGUX/bower-designsystem/issues/2) and the readme.md for updates on the bower install.

Thanks again!
