### ISSUE TITLE
url guidance

### ISSUE THREAD

**Issue by rdukeshier** [PBGUX/bower-designsystem#13]
Does design system provide any url guidelines/best-practices?  Specifically, I'm curious as to best practice for including/excluding hyphens in the non-domain part of a url.  

For example, should we prefer:  www.mydomain.com/myappname
or:  www.mydomain.com/my-app-name

It seems that [google](https://support.google.com/webmasters/answer/76329?hl=en) provides guidance recommending the latter.  The sample app in DS seems to do the same:
     http://sampleapp1.designsystem.pitneycloud.com/#/add-customer

However, the design system itself does not:
    https://designsystem.pitneycloud.com/#/popoverstooltips

Thoughts?

**Comment by cpileggi** [comment]
Hey Rick,

This is something we can't discussed with the team that I know of. The google guidance sounds solid, and I can see us adding it to our content guidance. I would follow their suggestions.

In the meantime I will ask the team. Thanks for the input. Happy Holidays!
Carla

**Comment by smlombardi** [comment]
We have adopted their guidelines for DS 3.2:  `http://localhost:8082/#/web/elements/menus`

We will be adding content to point this out as well.
