### ISSUE TITLE
Update npm package to v3.1

### ISSUE THREAD

**Issue by azanov** [PBGUX/bower-designsystem#14]
Hi,

would be great if you can update the NPM package to the latest version. Currently it is 3.0.2. Moreover it is still affected by this issue: https://github.com/PBGUX/bower-designsystem/issues/11 . Just updating the version in `package.json` is not enough, you have to publish the package.

Greets,

Pavel

**Comment by smlombardi** [comment]
We are in the middle of the 3.1 launch, and have not announced it yet since we are obviously now finished.

**Comment by smlombardi** [comment]
BTW, this is now published
