### ISSUE TITLE
Gap after footer due to wrong padding

### ISSUE THREAD

**Issue by azanov** [PBGUX/bower-designsystem#15]
In v3.1, there's a gap after the footer:

![image](https://cloud.githubusercontent.com/assets/927098/21266081/c99a785a-c3a4-11e6-9e3e-8122d535c6ba.png)

![image](https://cloud.githubusercontent.com/assets/927098/21266098/d6c21416-c3a4-11e6-82ec-e513fc299d20.png)

This happens because of wrong padding set on the footer tag:

```
footer {
  ...
  padding: 7px 0;
  ...
}
```

You can fix it by setting the footer padding to `0` and updating the `padding-top` on `footer .container > div` to `18px` (just an approx. value which looks well):

```
footer {
  ...
  padding: 0;

  ...

  .container, .container-fluid {

     ...
     > div {
       padding: 18px 20px 16px 0; // 76px high, DS 3
     }
     ...

  }
}
```

**Comment by smlombardi** [comment]
I do not see this, on any Mac browser nor on IE11 or IE Edge on Windows 10.

![screen shot 2016-12-16 at 1 00 50 pm](https://cloud.githubusercontent.com/assets/835148/21273054/d12940ac-c38f-11e6-812a-d6f7aab239bd.png)

**Comment by azanov** [comment]
The screenshots have been taken in Chrome 51 on Windows 7. However, the issue was gone after upgrading to version 55. I'm closing the issue
