### ISSUE TITLE
Drag/Drop list

### ISSUE THREAD

**Issue by shawnss** [PBGUX/bower-designsystem#16]
Would it help to have a visual indicator in a list of items to let users know items can be re-arranged by drag/drop? In the example provided in the [demo](https://designsystem.pitneycloud.com/#/dragdrop#dragBetweenLists) there is no indication to user that items can move until mouse is moved over an item.  See the image for an example.
Thanks.
![capture](https://cloud.githubusercontent.com/assets/7524790/21625753/2b0ce57a-d1db-11e6-8fe2-fb4f5505a0cb.PNG)

**Comment by cpileggi** [comment]
Hey Shawn,

Great idea. We just picked up a 3rd party plugin for this, but I will add a story to see if it can be modified to add the visual cue.

Thanks,
Carla

**Comment by smlombardi** [comment]
This will be in 3.2.0

![screen shot 2017-03-08 at 9 55 16 am](https://cloud.githubusercontent.com/assets/835148/23708837/5e3236f8-03e5-11e7-8f52-80fd1017e431.png)
