### ISSUE TITLE
Styling issue with type-ahead. Active option is unreadable due to background color

### ISSUE THREAD

**Issue by foxindabox** [PBGUX/bower-designsystem#19]
![image](https://cloud.githubusercontent.com/assets/7986504/22415736/aae6c026-e6ef-11e6-90f1-34d9495b3d59.png)

ishan.misra@pb.com

**Comment by smlombardi** [comment]
Unable to reproduce using latest Design System

![screen shot 2017-03-08 at 9 51 48 am](https://cloud.githubusercontent.com/assets/835148/23708708/e1531a4e-03e4-11e7-89cf-430277d2b438.png)
