### ISSUE TITLE
component name

### ISSUE THREAD

**Issue by rdukeshier** [PBGUX/bower-designsystem#2]
We just got around to trying this out.  All seems to be working great.  My only quibble is on the component name "bower-designsystem".  Of the 30+ bower components we currently use, this is the only one that has "bower" in it's name.  

![image](https://cloud.githubusercontent.com/assets/5713608/10823840/903a2d68-7e2b-11e5-8a15-3d369d51401a.png)

It just looks a bit out of place and seems a little redundant.  "designsystem" or "design-system" would be best IMO.  Maybe throw a "pb-" prefix on there if necessary.

**Comment by danielcollettepb** [comment]
I changed the bower.json name to pb-designsystem, and registered under bower as the same, you'll have to use #master to get the change temporarily:

`bower install pb-designsystem#master`

I am leaving `bower-designsystem` registered for now so I can let other apps know of the change, will remove it in the future.

Thanks!

**Comment by nickroberts** [comment]
Looks like it works ok, the only thing I notice is that the bower package is still named `bower-designsystem`.

I know we wanted to make sure we left it so it doesn't break anyone right now, but I thought it would name the package `pb-designsystem`.

Otherwise, it works great.

On a side note, I like `pb-design-system` myself :smiling_imp:

Here is what gets entered into the `bower.json` file:

```
// removed for brevity
"dependencies": {
  // removed for brevity
  "bower-designsystem": "pb-designsystem#~2.1.1"
  // removed for brevity
}
// removed for brevity
```

This causes 0 issues, other than the fact that the folder is still named `bower-designsystem`.

**Comment by danielcollettepb** [comment]
@nickroberts I renamed with the dash, and reregistered with bower. Try installing from master to see the changes:

`bower install pb-design-system#master`

You should see in bower.json:

```
  "dependencies": {
    "pb-design-system": "master"
  }
```

and this in the bower_components:

![image](https://cloud.githubusercontent.com/assets/6116867/10834665/a45f17d6-7e71-11e5-85f5-5c7ecab39328.png)

Thanks for the help!

**Comment by nickroberts** [comment]
Works when installing from master.

Forgot that it wasn't tagged, yet :crying_cat_face:

Also, I'm not sure if I actually had to do this or not, but I also ran `bower cache clean` to make sure nothing was cached.

<img width="307" alt="screen shot 2015-10-29 at 7 31 00 pm" src="https://cloud.githubusercontent.com/assets/972330/10834886/9de3079e-7e73-11e5-8170-f997eb29d258.png">

**Comment by danielcollettepb** [comment]
The v2.1.1 release is updated, you can install with:

`bower install pb-design-system --save`

Thanks @rdukeshier and @nickroberts, this is much better!
