### ISSUE TITLE
Navbar menu with active class does not fit in, with the rest of the options.

### ISSUE THREAD

**Issue by foxindabox** [PBGUX/bower-designsystem#20]
![image](https://cloud.githubusercontent.com/assets/7986504/22415798/0d6565c2-e6f0-11e6-9fc1-a404e6d6b4ff.png)

ishan.misra@pb.com

**Comment by foxindabox** [comment]
Solved it with class "open" instead of "active"

**Comment by smlombardi** [comment]
OK, but please note that we don't currently support showing the "active" menu item in the DS
