### ISSUE TITLE
Issues with btn-group and tooltip 

### ISSUE THREAD

**Issue by ldaug** [PBGUX/bower-designsystem#21]
If you have a tooltip on the last button in a btn-group and hover so the tooltip is displayed the rounded corners go away.

No tooltip:
![image](https://cloud.githubusercontent.com/assets/7534439/22759546/d3a42b1a-ee20-11e6-93b4-41e068b19fda.png)

Tooltip:
![image](https://cloud.githubusercontent.com/assets/7534439/22759567/e78084e4-ee20-11e6-8331-572c55a555d4.png)

`<div class="btn-group">
      <button id="undoButton" class="btn btn-default" ng-click="ctrl.undo()" ng-disabled="!ctrl.canUndo" uib-tooltip="{{'hub.canvas.menu.undo' | translate}}" tooltip-placement="bottom" tooltip-trigger="'focus blur mouseenter mouseleave'">
        <i class="nc-icon-mini arrows-2_corner-left-round"></i>
      </button>
``
      <button id="redoButton" class="btn btn-default" ng-click="ctrl.redo()" ng-disabled="!ctrl.canRedo" uib-tooltip="{{'hub.canvas.menu.redo' | translate}}" tooltip-placement="bottom" tooltip-trigger="'focus blur mouseenter mouseleave'">
        <i class="nc-icon-mini arrows-2_corner-right-round"></i>
      </button>
    </div>`

Note I had issues inserting the html, but it should all be there.

**Comment by smlombardi** [comment]
Try using `tooltip-append-to-body` on the element with the tooltip

See https://angular-ui.github.io/bootstrap/#!#tooltip for details.
