### ISSUE TITLE
Icon Button Group

### ISSUE THREAD

**Issue by ldaug** [PBGUX/bower-designsystem#22]
A few people have remarked on this, so I am bring it up. Is there a reason the icons are not centered vertically?

![image](https://cloud.githubusercontent.com/assets/7534439/22804893/243059b4-eee9-11e6-98b9-eda4f8ef3c0f.png)

Thanks,
Luke

**Comment by smlombardi** [comment]
They are centered, it's just the way the characters in the icon font "sit" on their baseline

**Comment by ldaug** [comment]
Then I would suggest we compensate for that. People looking do not care about details like that. Obviously not a huge issue, but again it has been commented on by internal users.

**Comment by shawnss** [comment]
They were centered in DS 3.0. They also grow bigger in DS3.1!
![ds3vsds31](https://cloud.githubusercontent.com/assets/7524790/24711251/63d9e29a-19ed-11e7-88d7-0220eb7e6951.png)

**Comment by smlombardi** [comment]
the type of buttons you are asking about are typically in a toolbar, wrapped in a toolbar class, and look like this:

![screen shot 2017-04-05 at 12 58 25 pm](https://cloud.githubusercontent.com/assets/835148/24717178/957de01e-19ff-11e7-8f58-7f5fe6f67636.png)

As you can see, those are both centered and not larger.  Looks like you may be using "regular" buttons, which are design to have text and icons with text.

![screen shot 2017-04-05 at 12 54 56 pm](https://cloud.githubusercontent.com/assets/835148/24717246/d1d539c2-19ff-11e7-9f5e-943d456b2f95.png)
