### ISSUE TITLE
Navbar response when browser width changes not working as expected

### ISSUE THREAD

**Issue by jrnorrisjr** [PBGUX/bower-designsystem#23]
[relay browser resizing.zip](https://github.com/PBGUX/bower-designsystem/files/827907/relay.browser.resizing.zip)

The attached file contains screenshots of what the navbar is doing when the browser window is resized.  Initially at 1280 px all of the elements are visible.  At around 1200 px the user name disappears.  At around 780 px the icons on the right side wrap on the toolbar and just a bit less than that the hamburger menu finally appears.

System is Relay Hub.  DS version is 3.1.3.

**Comment by smlombardi** [comment]
The name turning into initials is by design.  We also can't support full responsive (i.e. any width) but it should support all set screen sizes (e.g. desktop, iPad portrait, iPad landscape, phones).

We have made this more robust in the next release, due April 13.

**Comment by jrnorrisjr** [comment]
Super.  I'll put the comment in the Jira bug that our QA filed.  The name just disappears - doesn't turn into initials but I think I didn't add that element to the header so I will do that.
