### ISSUE TITLE
pbds-checkbox misaligned in table row

### ISSUE THREAD

**Issue by jrnorrisjr** [PBGUX/bower-designsystem#24]
The attached screenshot shows the issue where the checkbox is not aligned with the text in the table row.  The actual code:
`<td class="text-center" style="padding-left: 0px; padding-right: 0px;">
                            <pbds-checkbox disabled="(job.deleted == true) || (job.mailed == true)" ng-model="job.deleteFlag" ng-change="psJobsCtrl.deleteJobChanged(job)"></pbds-checkbox>
                        </td>`
Screenshot:
![pbds-checkbox alignment](https://cloud.githubusercontent.com/assets/8123985/24375307/d5d7417e-1305-11e7-9257-bdc5a5a7171a.png)

**Comment by smlombardi** [comment]
Bootstrap adds 10px margin above and below something with class="checkbox"

For now, see https://plnkr.co/edit/a9swQdW1fghvCuYNf8DG?p=preview

I added a class on the `td` and added a class to the css:

```css
.checkbox-cell .checkbox {
  margin: 0;
}
```

We will look at a better solution in the next release.

**Comment by jrnorrisjr** [comment]
Thanks Steve.  You are quick!
Jim

On Mar 27, 2017 16:30, "Steve Lombardi" <notifications@github.com> wrote:

Bootstrap adds 10px margin above and below something with class="checkbox"

For now, see https://plnkr.co/edit/a9swQdW1fghvCuYNf8DG?p=preview

I added a class on the td and added a class to the css:

.checkbox-cell .checkbox {
  margin: 0;
}

We will look at a better solution in the next release.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PBGUX/bower-designsystem/issues/24#issuecomment-289576287>,
or mute the thread

**Comment by jrnorrisjr** [comment]
Hi Steve,

That made it worse.  The checkbox is now at the bottom of the row.
Screenshot attached.

Jim

**Comment by smlombardi** [comment]
Follow what's in the plunker.  It works fine there.

**Comment by jrnorrisjr** [comment]
I did follow what's in the plunker which you can see in the screenshot.
Checkboxes moved down so something else must be affecting it.
