### ISSUE TITLE
Toolbar button CSS selectors "too tight"

### ISSUE THREAD

**Issue by rcollette** [PBGUX/bower-designsystem#28]
If you implement a toolbar button as a directive, we lose styling because of the element used to create the directive.   We lose spacing between buttons, disabled styling, etc.

Example markup that doesn't work.

```html
<div class="toolbar">
    <div class="toolbar-left">
        <pb-address-book-modal-lookup
                pb-on-address-selection="vm.onSelectFromAddressBook(addresses)"
                pb-address-type="Recipient" pb-multi-select="true" pb-max-addresses="5"
                pb-iso-country="'US'" pb-button-style="toolbar" pb-disabled="vm.continueDisabled">
            <button id="createLabel-addressBook-recipient"
                    class="btn btn-link addressbook-icon spacer-bottom-sm-pbdevice"
                    type="button"
                    data-ng-class="{'btn-default': vm.connectPlus, 'btn-icon': vm.buttonStyle==='btn-icon',}"
                    data-ng-click="vm.addressBookClick()" data-ng-disabled="vm.isAddressBookClickDisabled"
                    data-uib-tooltip="Choose from Address Book" data-tooltip-placement="top"
                    data-tooltip-append-to-body="true"
                    disabled="disabled"><i class="pbfont pbfont-addressbook"></i></button>
        </pb-address-book-modal-lookup>
    </div>
</div>
```
Can we relax the selectors to use descendant rather than child selectors?

**Comment by smlombardi** [comment]
FWIW, the reason I used sibling selectors was to only apply a left margin on a button if a button was already to the left of it. Applying a margin to all buttons inside a toolbar opens an issue that the first (or last) button in the toolbar should not have a margin.  So a simple `.toolbar .btn` wouldn't do.  I will likely use `.toolbar-left .btn` and `.toolbar-right .btn` with right and left margins, respectively.

**Comment by smlombardi** [comment]
This has been updated for 4.0 to include other block items.
