### ISSUE TITLE
Linking to variable sheet causes gulp error

### ISSUE THREAD

**Issue by SamSwartzPB** [PBGUX/bower-designsystem#3]
Once I link to the new pb-design-system variables I get an error in the gulp stream

in `variable.scss`, at line **544** there is the following style:
`$state-danger-border: rgba(244, 183, 183, 100);`

The error says that `rgba` can only accept an alpha value between 0 & 1
changing `100` to `1` fixes the issue

**Comment by smlombardi** [comment]
THat's really odd.  The linter is ok with 100, which is wrong, but doesn't like 1 or 1.0.

Fortunately, if the alpha is 1, you don't need it.  Use `$state-danger-border: rgb(244, 183, 183);`

I will fix the main sass file.

**Comment by SamSwartzPB** [comment]
Thanks Steve! Any idea when I can pull in the new DS bower component?

**Comment by lombardi-gux** [comment]
Dan just updated everything to 2.2
