### ISSUE TITLE
Responsive nav menu with hamburger menu

### ISSUE THREAD

**Issue by jrnorrisjr** [PBGUX/bower-designsystem#31]
The example in DS only shows icons and not the dropdown menus for nav items in the header that move to the hamburger menu when the browser is resized.  Can you expand the DS example code to show how the dropdown menus work when moved from the header to the hamburger menu?

**Comment by smlombardi** [comment]
They would work the same as the menus on the current design system site (resize it to see).  It's basically automatically handled by Bootstrap's CSS; the menus just fall under their header and expand.

See also http://getbootstrap.com/components/#navbar

**Comment by jrnorrisjr** [comment]
Hi Steve,

I still think this is an issue.  The DS demo does not work when the brower
is resized and the header icons are moved below the icons in the hamburger
menu.  You can try it yourself:
https://designsystem.pitneycloud.com/#/push/icon

As you can see in the attached screenshot, clicking on the icons that were
moved into the hamburger menu do nothing even though they indicate it is
selected.  I did see them working on the DS website itself but that does
not use the hamburger menu.

Jim

**Comment by smlombardi** [comment]
I don't get it, it works for  me.  Here, the sample header is set to iPhone 7 size.  Click "settings" opens the settings menu.

![screen shot 2017-06-26 at 10 45 48 am](https://user-images.githubusercontent.com/835148/27545032-ca78f270-5a5c-11e7-9c98-006b794d62be.png)

**Comment by jrnorrisjr** [comment]
Yes but try the demo of the one that has the hamburger menu.  There are no sub-menus when the icons move into the hamburger menu.  In the example code for the demo it is dynamically adding the header icons but the example code just adds the icons and no dropdowns.

**Comment by smlombardi** [comment]
I know.  we never did that one. we assumed people would use the header sample above, and combine it.
