### ISSUE TITLE
Drop-downs appear over (not beneath) input field on EDGE

### ISSUE THREAD

**Issue by seanprince** [PBGUX/bower-designsystem#34]
I'm noticing a difference in behaviour in drop-downs on EDGE (Microsoft Edge 40.15063.0.0, Microsoft EdgeHTML 15.15063) vs Chrome (Version 59.0.3071.115 (Official Build) (64-bit)).

On Chrome:
![image](https://user-images.githubusercontent.com/7532924/28827765-77739b3a-76c6-11e7-82d5-0f15b28c5c5b.png)

On EDGE:
![image](https://user-images.githubusercontent.com/7532924/28827867-da97e1da-76c6-11e7-81f5-46be38a1da29.png)

ie the drop-down appears over the input field on EDGE, and is styled incorrectly.

To see the issue in a live application, go here - http://152.144.142.179:8086/bna-client/#/selections/609d5521-d9c7-47e1-b72c-9b1b402a1f72 .

**Comment by danielcollettepb** [comment]
This the default behavior of Edge with a select menu. Here is a screenshot of the Design System site Web > Menus page. Firefox will have different interaction/visual look as well. These are items that we cannot change via CSS.

![image](https://user-images.githubusercontent.com/6116867/29085197-8b425b44-7c3c-11e7-8248-e07c732b90ba.png)
