### ISSUE TITLE
Should the $pb-magenta reference in _mixins.scss be updated?

### ISSUE THREAD

**Issue by Xorandnotor** [PBGUX/bower-designsystem#36]
https://github.com/PBGUX/bower-designsystem/blob/master/sass/settings/_mixins.scss#L32

Line 32 of _mixines.scss has a reference to $pb-magenta, which it looks like was deprecated.  Should this now be $pb-magenta-500?

**Comment by smlombardi** [comment]
You could use either, although `$pb-magenta-500` is indeed preferred.

In variables.scss, you'll see that, for safety, I mapped the names without the numbers to the 500s:  `$pb-magenta: $pb-magenta-500;`
