### ISSUE TITLE
design_system.css file does not contain class '.doc-hero'

### ISSUE THREAD

**Issue by denishpb** [PBGUX/bower-designsystem#9]
I am trying to get the breadcrumb and page title in hero header. But the design_system.css file inside dist folder does not contain .doc-hero class.

**Comment by smlombardi** [comment]
.doc-hero is for the large gradient bar on the design system site only.  that design element is not intended to be used on actual applications.

**Comment by denishpb** [comment]
no problem. But the css file does contain selectors for internal hero elements, like breadcrumb and page title.

**Comment by smlombardi** [comment]
because page titles and breadcrumbs _are_ items that would be used on apps.  It's the "hero" band which is unique to the DS web site.

**Comment by denishpb** [comment]
ok thanks.
